### Get authentication token
# @name login
POST http://localhost:8080/api/auth/authenticate
Content-Type: application/json

{
  "username": "Yassin4",
  "password": "Zaqwe123!"
}

<> 2025-04-04T080529.200.json
<> 2025-03-26T144732.200.json
<> 2025-03-25T140742.200.json
<> 2025-03-25T140724.200.json
<> 2025-03-25T140650.200.json
<> 2025-03-25T140642.200.json
<> 2025-03-25T140557.200.json
<> 2025-03-25T140513.200.json
<> 2025-03-25T140429.200.json
<> 2025-03-25T140420.200.json
<> 2025-03-25T140408.200.json
<> 2025-03-25T140321.200.json
<> 2025-03-25T140040.200.json
<> 2025-03-25T140020.401.json
<> 2025-03-25T140017.401.json
<> 2025-03-25T140008.401.json

### Store the auth token in a variable
@authToken = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJZYXNzaW40IiwiaWF0IjoxNzQ0NzIyODQ4LCJleHAiOjE3NDQ3NTg4NDh9.xiEp1-3KmTMkosl2A3XjGUzgIGnVpyMXOP6U1Z-Oe7U


### Create a BDT
POST http://localhost:8080/api/bdt/
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "nom": "uklu",
  "risques": [],
  "auditSecu": [],
  "complementOuRappels": [
    {
      "complement": "llilll",
      "respect": false
    },
    {
      "complement": "klili",
      "respect": false
    },
    {
      "complement": "jilkyghu",
      "respect": false
    }
  ],
  "chantier": {
    "id": 405
  },
  "entrepriseExterieure": {
    "id": 22
  }
}


### Link BDT to risque
POST http://localhost:8080/api/bdt/6/risque/14
Authorization: Bearer {{authToken}}

### Link BDT to audit
http://localhost:8080/api/pdp/65/objectAnswered/RISQUE
Authorization: Bearer {{authToken}}