spring:
  output:
    ansi:
      enabled: always
  application:
    name: PDPBackend
  datasource:
    url: jdbc:postgresql://localhost:5432/pdpdb
    username: Yassin
    password: 123123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: never
server:
  port: 8080
  address: 0.0.0.0
logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql:
                BasicBinder: trace
    sql: debug