create table users (
                       id bigint generated by default as identity primary key,
                       email varchar(255),
                       fonction varchar(255),
                       notel varchar(255),
                       password varchar(255),
                       username varchar(255)
);

create table audit_secu (
                            id bigint generated by default as identity primary key,
                            description varchar(255),
                            image_data blob,
                            mime_type varchar(255),
                            title varchar(255)
);

create table dispositif (
                            id bigint generated by default as identity primary key,
                            description varchar(255),
                            image_data blob,
                            mime_type varchar(255),
                            title varchar(255)
);

create table entreprise (
                            id bigint generated by default as identity primary key,
                            description varchar(255),
                            image_data blob,
                            mime_type varchar(255),
                            no_tel_de_medcin varchar(255),
                            nom_de_medecin varchar(255),
                            nom varchar(255),
                            numerotelephone varchar(255),
                            raisonsociale varchar(255),
                            type varchar(255) check (type in ('EU', 'EE'))
);

create table localisation (
                              id bigint generated by default as identity primary key,
                              code varchar(255),
                              description varchar(255),
                              nom varchar(255)
);

create table chantier (
                          id bigint not null primary key,
                          date_debut timestamp,
                          date_fin timestamp,
                          effectif_maxi_sur_chantier int,
                          is_annuelle boolean,
                          nb_heurs int,
                          nom varchar(255),
                          nombre_interimaires int,
                          operation varchar(255),
                          status varchar(255) check (status in ('PENDING_PDP', 'PENDING_BDT', 'ACTIVE', 'COMPLETED', 'CANCELED', 'INACTIVE_TODAY')),
                          travaux_dangereux boolean,
                          donneurdordre_id bigint references users,
                          entreprise_utilisatrice_id bigint references entreprise,
                          localisation_id bigint references localisation
);

create table chantier_entreprise_exterieurs (
                                                chantier_id bigint not null references chantier,
                                                entreprise_exterieurs_id bigint not null references entreprise
);

create table document (
                          id bigint generated by default as identity primary key,
                          action_type varchar(255) check (action_type in ('NONE', 'SIGHNATURES_MISSING', 'PERMIT_MISSING')),
                          creation_date date,
                          date date,
                          status varchar(255) check (status in ('DRAFT', 'ACTIVE', 'COMPLETED', 'EXPIRED', 'CANCELED', 'NEEDS_ACTION')),
                          chantier_id bigint references chantier,
                          entreprise_exterieure_id bigint references entreprise
);

create table bdt (
                     complement_ou_rappels clob,
                     nom varchar(255),
                     id bigint not null primary key references document
);

create table object_answered (
                                 id bigint generated by default as identity primary key,
                                 answer boolean,
                                 ee boolean,
                                 eu boolean,
                                 object_id bigint,
                                 object_type varchar(255) check (object_type in ('RISQUE', 'DISPOSITIF', 'PERMIT', 'AUDIT', 'ANALYSE_DE_RISQUE')),
                                 document_id bigint references document
);

create table pdp (
                     date_inspection timestamp,
                     date_prev timestamp,
                     date_prevenircssct timestamp,
                     en_journee boolean,
                     en_nuit boolean,
                     samedi boolean,
                     horaires_details varchar(255),
                     icpdate timestamp,
                     energie boolean,
                     restaurant boolean,
                     sanitaires boolean,
                     vestiaires boolean,
                     id bigint not null primary key references document,
                     entreprisedinspection_id bigint references entreprise
);

create table permit (
                        id bigint generated by default as identity primary key,
                        description varchar(255),
                        image_data blob,
                        mime_type varchar(255),
                        title varchar(255),
                        pdf_data blob
);

create table risque (
                        id bigint generated by default as identity primary key,
                        description varchar(255),
                        image_data blob,
                        mime_type varchar(255),
                        title varchar(255),
                        permit_id bigint,
                        travaille_dangereux boolean,
                        travaille_permit boolean
);

create table analyse_de_risque (
                                   id bigint generated by default as identity primary key,
                                   deroulement_des_taches varchar(255),
                                   mesures_de_prevention varchar(255),
                                   moyens_utilises varchar(255),
                                   risque_id bigint references risque
);

create table object_answered_entreprises (
                                             id bigint generated by default as identity primary key,
                                             ee boolean,
                                             eu boolean,
                                             analyse_de_risque_id bigint references analyse_de_risque
);

create table worker (
                        id bigint not null primary key,
                        nom varchar(255),
                        prenom varchar(255),
                        entreprise_id bigint references entreprise
);

create table document_signature (
                                    id bigint generated by default as identity primary key,
                                    active boolean not null,
                                    signature_date timestamp not null,
                                    image_data blob,
                                    mime_type varchar(255),
                                    document_id bigint not null references document,
                                    worker_id bigint not null references worker
);

create table signature (
                           id bigint generated by default as identity primary key,
                           date timestamp,
                           nom varchar(255),
                           prenom varchar(255),
                           image_data blob,
                           mime_type varchar(255),
                           document_id bigint references document,
                           worker_id bigint references worker
);

create table worker_chantier_selection (
                                           id bigint generated by default as identity primary key,
                                           is_selected boolean,
                                           selection_date timestamp,
                                           selection_note varchar(255),
                                           chantier_id bigint references chantier,
                                           selected_by bigint references users,
                                           worker_id bigint references worker
);

create table worker_chantiers (
                                  worker_id bigint not null references worker,
                                  chantiers_id bigint not null references chantier
);

create table worker_pdps (
                             worker_id bigint not null references worker,
                             pdps_id bigint not null references pdp
);

create table activity_log
(
    id bigint generated by default as identity
        primary key,
    action_key varchar(255) not null,
    description varchar(500),
    details varchar(255),
    target_entity_id bigint,
    target_entity_type varchar(255),
    timestamp timestamp(6) not null,
    actor_user_id bigint
        constraint fkqiqeugw7m55wio79dptt5solr
            references users
);
